name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # إنشاء مشروع نقي ونقل كود main.dart إليه ثم البناء
      - run: |
          mkdir temp_build
          cd temp_build
          flutter create --platforms=android receiver_app
          cp ../lib/main.dart receiver_app/lib/main.dart
          cd receiver_app
          flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: temp_build/receiver_app/build/app/outputs/flutter-apk/app-debug.apk
          
